with-expecter: true
filename: "mock_{{.InterfaceNameSnake}}.go"
dir: "{{.InterfaceDir}}/mocks"
mockname: "{{.Mock}}{{.InterfaceName}}"
outpkg: "{{.PackageName}}"
packages:
  github.com/openshift/lvm-operator/v4/internal/controllers/vgmanager/lsblk:
    interfaces:
      LSBLK:
  github.com/openshift/lvm-operator/v4/internal/controllers/vgmanager/lvm:
    interfaces:
      LVM:
  github.com/openshift/lvm-operator/v4/internal/controllers/vgmanager/lvmd:
    interfaces:
      Configurator:
  github.com/openshift/lvm-operator/v4/internal/controllers/vgmanager/wipefs:
    interfaces:
      Wipefs:
  github.com/openshift/lvm-operator/v4/internal/controllers/vgmanager/dmsetup:
    interfaces:
      Dmsetup:
