apiVersion: v1
kind: Namespace
metadata:
  annotations:
    workload.openshift.io/allowed: "management"
  labels:
    app.kubernetes.io/name: lvms-operator
    security.openshift.io/scc.podSecurityLabelSync: "false"
    pod-security.kubernetes.io/enforce: "privileged"
    pod-security.kubernetes.io/warn: "privileged"
    pod-security.kubernetes.io/audit: "privileged"
    openshift.io/cluster-monitoring: "true"
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator
  namespace: system
  annotations:
    target.workload.openshift.io/management: '{"effect": "PreferredDuringScheduling"}'
  labels:
    app.kubernetes.io/name: lvms-operator
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: lvms-operator
  replicas: 1
  template:
    metadata:
      annotations:
        target.workload.openshift.io/management: '{"effect": "PreferredDuringScheduling"}'
      labels:
        app.kubernetes.io/name: lvms-operator
        app.kubernetes.io/part-of: lvms-provisioner
        app.kubernetes.io/component: lvms-operator
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - command:
        - /lvms
        - operator
        args:
        - --leader-elect
        image: controller:latest
        # if name is changed here, same should be reflected in 'controller/defaults.go'
        # search for 'ContainerName'
        name: manager
        securityContext:
          allowPrivilegeEscalation: false
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            cpu: 5m
            memory: 75Mi
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        volumeMounts:
          - mountPath: /run/topolvm
            name: "socket-dir"
      - name: csi-resizer
        image: "k8s.gcr.io/sig-storage/csi-resizer:v1.6.0"
        args:
          - --csi-address=/run/topolvm/csi-topolvm.sock
        volumeMounts:
          - mountPath: /run/topolvm
            name: "socket-dir"
        resources:
          requests:
            cpu: 1m
            memory: 35Mi
      volumes:
        - name: socket-dir
          emptyDir: {}
      serviceAccountName: lvms-operator
      terminationGracePeriodSeconds: 60
