resources:
# All RBAC will be applied under this service account in
# the deployment namespace. You may comment out this resource
# if your manager will use a service account that exists at
# runtime. Be sure to update RoleBinding and ClusterRoleBinding
# subjects if changing service account names.
- service_account.yaml
- role.yaml
- role_binding.yaml
- leader_election_role.yaml
- leader_election_role_binding.yaml
# topolvm-controller rbac
- topolvm_controller_service_account.yaml
- topolvm_controller_role.yaml
- topolvm_controller_role_bindings.yaml
# lvm-node metric rbac
- lvms_node_role_n_rolebindings.yaml
# Comment the following 4 lines if you want to disable
# the auth proxy (https://github.com/brancz/kube-rbac-proxy)
# which protects your /metrics endpoint.
- auth_proxy_role.yaml
- auth_proxy_role_binding.yaml
- auth_proxy_client_clusterrole.yaml
- vg_manager_role.yaml
- vg_manager_role_binding.yaml
- vg_manager_clusterrole.yaml
- vg_manager_clusterrole_binding.yaml
- vg_manager_service_account.yaml
