---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: topolvm-controller
subjects:
  - kind: ServiceAccount
    name: lvms-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: topolvm-controller
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: topolvm-csi-provisioner
subjects:
  - kind: ServiceAccount
    name: lvms-operator
roleRef:
  kind: ClusterRole
  name: topolvm-csi-provisioner
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: topolvm-csi-resizer
subjects:
  - kind: ServiceAccount
    name: lvms-operator
roleRef:
  kind: ClusterRole
  name: topolvm-csi-resizer
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: topolvm-leader-election
subjects:
  - kind: ServiceAccount
    name: lvms-operator
roleRef:
  kind: Role
  name: topolvm-leader-election
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: topolvm-csi-provisioner
subjects:
  - kind: ServiceAccount
    name: lvms-operator
roleRef:
  kind: Role
  name: topolvm-csi-provisioner
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: topolvm-csi-resizer
subjects:
  - kind: ServiceAccount
    name: lvms-operator
roleRef:
  kind: Role
  name: topolvm-csi-resizer
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: topolvm-csi-snapshotter
subjects:
  - kind: ServiceAccount
    name: lvms-operator
roleRef:
  kind: ClusterRole
  name: topolvm-csi-snapshotter
  apiGroup: rbac.authorization.k8s.io
---
