apiVersion: lvm.topolvm.io/v1alpha1
kind: LVMCluster
metadata:
  name: my-lvmcluster
spec:
  storage:
    deviceClasses:
    - name: vg1
      default: true
      deviceSelector:
        paths:
          - /dev/vdb
          - /dev/vdc
          - /dev/vdd
          - /dev/vde
      RAIDConfig:
        type: raid10
        mirrors: 1
        stripes: 2
        sync: true
      thinPoolConfig:
        name: thin-pool-1
        sizePercent: 90
        overprovisionRatio: 10
      fstype: xfs
